### 1) 헬스 체크
GET http://43.201.40.98:8080/health


### 2) 플레이어1 접속
#P1: 55f2cb86bc864e2c989b9a6d4a0a42f9
POST http://43.201.40.98:8080/connect
Content-Type: application/json

{
  "playerName": "seonseo"
}

### 3) 플레이어2 접속
#P2: 50054ccb9a544e08ba642d79e3a486be
POST http://43.201.40.98:8080/connect
Content-Type: application/json

{
  "playerName": "pse"
}

### 4) 플레이어3 접속
#P3: 1777a261358640f187711363c8cf8f91
POST http://43.201.40.98:8080/connect
Content-Type: application/json

{
  "playerName": "hhh"
}

### 5) 방 생성
# Room ID: 583c43909867427fa12d821d54618af5
# Invite Code: JYZ95G

POST http://43.201.40.98:8080/room/create
Content-Type: application/json

{
  "playerId": "55f2cb86bc864e2c989b9a6d4a0a42f9",
  "maxPlayers": 2
}


### 6) 방 입장 (플레이어2 초대코드로 입장)
POST http://43.201.40.98:8080/room/join
Content-Type: application/json

{
  "playerId": "f76726e5347b47bcb7993bcc1a74eca4",
  "inviteCode": "JYZ95G"
}
    
### 7) 방 입장 (플레이어3 초대코드로 입장)
POST http://43.201.40.98:8080/room/join
Content-Type: application/json

{
  "playerId": "1777a261358640f187711363c8cf8f91",
  "inviteCode": "KN43XC"
}

